name: CI - Test Flask App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica il codice dal repository
        uses: actions/checkout@v6

      - name: Configura Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Installa le dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui i test
        run: pytest
